---
title: "git_01"
author: "Christina Jilavdaryan"
date: "09/23/21"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with commits to different branches
Our project will be done using a sequence of save and commits and branch actions.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
<!--Put the first five lines of a poem by Lewis Carrol in this section!-->


"Just the place for a Snark!" the Bellman cried,  
   As he landed his crew with care;  
Supporting each man on the top of the tide  
   By a finger entwined in his hair.  

"Just the place for a Snark! I have said it twice:  


## Second Verse
<!--Put the first five lines of a poem by Robert Frost here!-->


I have been one acquainted with the night.  
I have walked out in rain—and back in rain.  
I have outwalked the furthest city light.  

I have looked down the saddest city lane.  
I have passed by the watchman on his beat  
And dropped my eyes, unwilling to explain.  


## Third Verse
<!--Put the first two verses of The Walrus and the Carpenter here!-->


"The sun was shining on the sea,  
      Shining with all his might:  
He did his very best to make  
      The billows smooth and bright —  
And this was odd, because it was  
      The middle of the night.  

The moon was shining sulkily,  
      Because she thought the sun  
Had got no business to be there  
      After the day was done —  
"It's very rude of him," she said,  
      "To come and spoil the fun."  


## Last Verse
<!--Put a short poem of your choice 8-20 lines,here!-->


'Let the light rain on her, the sweet Spring, till  
She teems with greenery in the warm air,  
Flower-hued, and vocal with the tender joy  
Of bleating lambs and young birds on the wing.'  
Thus on the cold hill doth the herdsman pray  
Beneath his frozen star; the milkmaid, too,  
As her raw hands take up the milking-pail,  
And the wind freezes in the red dawn near: ?  
'Come, Spring, earth's sap, and mount in me until  
I bloom, a rose of love: smile in mine eyes  
Till my love from his wintry hill shall see  
The star of youth, and leap into my arms!  
O Spring, sweet Spring! but hear my prayer, and I  
Shall build thee bowers of roses on the hill,  
And all the summer there with bird and bee  
Shall joy feast in the beauty of our love!'  
Thus do they chant the wintry time away  
In hill and vale, the two who look to when  
The warmth of beauty takes life's wonder on,  
And the rose of the flesh shall bloom for them.  

